/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    NewOrder: typeof import('./src/components/NewOrder.vue')['default']
    OrdersList: typeof import('./src/components/OrdersList.vue')['default']
    ProductsList: typeof import('./src/components/ProductsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
